### PR TITLE
Remove pureconfig in favor of circe-config

### PR DESCRIPTION
**Pull request by zakpatterson**
Addresses #120

### CODE REVIEW

**Comment by zakpatterson** [comment]
hold off on merging, I'm lobbying for this in circe-config: https://github.com/circe/circe-config/pull/29

**Comment by pauljamescleary** [comment]
We should update the README too (anywhere else that uses pureconfig).

**Comment by zakpatterson** [comment]
It looks like the default load PR will get into circe-config soon, so if you agree I think it makes sense to just merge this now and then revise usage once scala-steward picks up a new release from circe-config.

**Comment by pauljamescleary** [comment]
@zakpatterson sounds good

**Pull request merged**
