### PR TITLE
kind-projector is published from the typelevel org now

### PR DESCRIPTION
**Pull request by SethTisue**
having this merged will be a minor help to the Scala community build,
which assumes the new org

### CODE REVIEW

**Comment by SethTisue** [comment]
oh, oops, I need to use the version that was published for 2.13.0-M5. fixing...

**Comment by SethTisue** [comment]
gah, you know what, this should just wait until y'all are on 2.13.0-RC1 or RC2 or final, never mind, I'll work around it in the community build confidence file for now

**Comment by zakpatterson** [comment]
@SethTisue Thanks for this, fyi: #181

**Comment by zakpatterson** [comment]
@SethTisue, so you know, #181 was just merged, and we're building on 2.13.0 now. Thanks!

**Comment by SethTisue** [comment]
@zakpatterson awesome! I'll try it in the Scala 2.13 community build, but I'll need to fix some dependencies first

```
[info] Project scala-pet-store-------------: DID NOT RUN (stuck on broken dependencies: doobie, tsec, tut)
```

**Comment by zakpatterson** [comment]
Yep all those were advanced a few times to get this build to work. I'm not at all clear on how the build actually happens, but it seems this replacement is also no longer needed: 

https://github.com/scala/community-builds/commit/1c1e70c5c96953af2985b239786041e7f646b9bd#diff-13924878884a607db34ef8aa8c07a253R2564

Anyway, totally happy to help let me know if you need anything else from us.

**Pull request closed without merging**
