### PR TITLE
Architecture improvements

### PR DESCRIPTION
**Pull request by DStranger**
Hi @pauljamescleary,

Thanks for this project, it's very interesting to see how you can build a project using Typelevel libraries for functional programming.
I've made some changes to the structure of the project, which are:
- business logic now lives in it's own package, clearly separated from the implementing code and infrastructure-related code
- code in the domain package is split by the feature it implements (users, pets, orders)

Result resembles the 'Onion Architecture', I suppose.
Hope this is useful!

### CODE REVIEW

**Comment by pauljamescleary** [comment]
Thanks for the PR!  I will take a look at it over the weekend :)

**Comment by pauljamescleary** [comment]
I am good with these changes.  Thank you for formalizing the split, looks a lot more like a traditional onion architecture.

Going to wait a few days to see if @fanf, @daddykotex, @cranst0n, or any others have any input.  If not, I will merge this early next week.

**Comment by cranst0n** [comment]
LGTM. Nice work @DStranger.

**Comment by daddykotex** [comment]
Honestly, it looks good.

The gain are not obvious for an application this size but they become once the application reach a certain size (I don't know if it will happen with a pet store, but who knows). This is a good idea since it shows best practices IMO 👍

**Comment by pauljamescleary** [comment]
Feeling around this code tonight for the first time.  Really like it, thanks @DStranger!

**Comment by DStranger** [comment]
Thanks guys, glad to be of help!

**Pull request merged**
